### ISSUE TITLE
Question about scale features

### ISSUE THREAD

**Issue by ZhouZijie77** [zjuluolun/BEVPlace#8]
Hello, thank you for sharing your excellent work. I'm a little confused about the scale features in your work.
You have mentioned in your paper that "Our main modification to GIFT is to remove the scale features since there is no scale difference between BEV images". However, after I read your code, I don't quite understand how the scale features are removed. It seems that the scale features are still in the input.
Can you explain it? Thanks!

**Comment by zjuluolun** [comment]
Hi! Sorry for the late response. In the early version of BEVPlace, the scale feature is reserved for fast development, but it actually does not influence much since there is no scale difference between BEV images. You could refer to our BEVPlace++ for a more concise implementation, which has been released with its training scripts now.
